### ISSUE TITLE
[Epic] Update to rrweb 2.0 in SDK and in sentry

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/rrweb#76]
See https://github.com/rrweb-io/rrweb/releases to track release status

Benefits

* Support for canvas
  * https://github.com/getsentry/sentry-javascript/issues/6519
  * Can we treeshake it out if `canvas` is not opt'ed in
* Support for cross origin iframes
  * https://github.com/getsentry/sentry-javascript/issues/7279 
* Less maintenance overhead with our own patched v1
* Fixes
  * https://github.com/getsentry/rrweb/issues/57
  * https://github.com/getsentry/sentry-javascript/issues/8469
  * https://github.com/getsentry/sentry-javascript/issues/8123

Risks:

* Still Alpha
* Package size is ~40% larger

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/team-replay/issues/25
- [x] Make sure the tests we added work on rrweb 2.0
- [ ] Assess treeshaking opportunities for features we don't use/need
- [x] Run agains the performance tool to verify change from 1.0
- [x] Update docs with new bundle size and overhead numbers
```

Related:
- https://github.com/getsentry/sentry-javascript/issues/7279
- https://github.com/getsentry/sentry-javascript/issues/6946

**Comment by mydea** [comment]
This is esp. interesting IMHO: https://github.com/rrweb-io/rrweb/pull/1127
> Refactor: Improve performance by 80% in a super large benchmark case.

**Comment by billyvg** [comment]
Released in 7.73.0!
